### PR TITLE
Update user agent to detect if request is coming from mobile device.

### LINKED ISSUE #3: Set Edge Mobile UA for Firefox Android

### PR DESCRIPTION
**Pull request by anaclumos**
Resolves #3

### CODE REVIEW

**Comment by anaclumos** [comment]
@rany2, can you confirm if the following build is working?

https://github.com/anaclumos/bing-chat-for-all-browsers/blob/edge-mobile/release/firefox.zip

**Comment by rany2** [comment]
It's impossible to test without you publishing it to AMO. Mozilla requires all add-ons be signed. In any case, it looks good to me

**Comment by rany2** [comment]
@anaclumos Good news, I figured out how to get firefox to run unsigned extensions. It works!

**Comment by anaclumos** [comment]
Awesome!

**Pull request merged**
